name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install buildozer
          sudo apt install -y openjdk-11-jdk
          sudo apt install -y libffi-dev
          sudo apt install -y python3-dev
          sudo apt install -y zip
          sudo apt install -y unzip
          sudo apt install -y git

      - name: Accept SDK licenses
        run: echo yes | sudo sdkmanager --licenses

      - name: Build with Buildozer
        run: |
          buildozer android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: bin/*.apk
