name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          # Nainstalujeme pár základních balíků
          sudo apt-get install -y python3 python3-pip openjdk-17-jdk unzip zip
          # Tady instalujeme buildozer, cython, a třeba kivy/kivymd
          pip3 install buildozer cython kivy kivymd pyjnius

      - name: Build with Buildozer
        run: |
          # Pokud není buildozer.spec, vytvoří se defaultní
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          # Samotný build APK v debug módu
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: battery_app_apk
          path: bin/*.apk
