name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip wget unzip zip openjdk-17-jdk
          # Zkusíme starší verzi p4a z prosince 2022
          pip install buildozer cython kivy kivymd pyjnius "python-for-android==2022.12.20"

      - name: Remove old sdk folder
        run: |
          # Pro jistotu smažeme starou instalaci SDK
          rm -rf .buildozer/android/platform/android-sdk

      - name: Build with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
