name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk zlib1g-dev

      - name: Set up Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools
          echo "ANDROID_HOME=$(realpath ~/android-sdk)" >> $GITHUB_ENV
          echo "$(realpath ~/android-sdk/cmdline-tools)/bin" >> $GITHUB_PATH

      - name: Install Android components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools"

      - name: Install Python dependencies
        run: |
          pip install "python-for-android==2024.01.21" buildozer kivy kivymd

      - name: Build APK
        run: |
          buildozer android clean
          buildozer android debug
