name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip wget unzip zip openjdk-17-jdk
          pip install buildozer cython kivy kivymd pyjnius 
          # (p4a se nainstaluje automaticky s buildozerem, 
          #  nebo můžeš pinovat starší verzi, to už je na tobě)

      # 1) Nainstalujeme commandline tools
      - name: Install cmdline-tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip
          mv cmdline-tools tools
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/tools/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/36.0.0-rc5" >> $GITHUB_ENV
          echo "SDKMANAGER=$HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager" >> $GITHUB_ENV

      # 2) Odsouhlasíme licence a nainstalujeme 36-rc5
      - name: Pre-install 36-rc5
        run: |
          source $GITHUB_ENV
          yes | $SDKMANAGER --licenses
          yes | $SDKMANAGER "platforms;android-33" "platform-tools" "build-tools;36.0.0-rc5"

      # 3) Pro jistotu smažeme starou sdk složku, aby se nestahovaly polovičaté soubory
      - name: Remove old sdk folder
        run: |
          rm -rf .buildozer/android/platform/android-sdk

      - name: Build with Buildozer
        run: |
          source $GITHUB_ENV
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
