name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk git zlib1g-dev

      - name: Clone python-for-android
        run: |
          git clone https://github.com/kivy/python-for-android.git
          cd python-for-android
          pip install -e .
          
      - name: Set Android environment
        run: |
          echo "ANDROID_SDK_ROOT=~/.android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=~/.android-ndk" >> $GITHUB_ENV

      - name: Build with Buildozer
        run: |
          pip install buildozer
          buildozer android clean
          buildozer android debug
